stages:
  - checklist
  - test
  
.checklist:
  image: alpine
  before_script:
    - apk add -q grep git

master branch:
  extends: .checklist
  stage: checklist
  script:
    - git remote update
    - if ! git log --pretty=format:"%H" | grep $(git log --pretty=format:"%H" -n 1 origin/master); then exit 1; fi
  except:
    - master

git conflicts:
  extends: .checklist
  stage: checklist
  script:
    - if grep -rni '^<<<<<<< H\EAD$'; then exit 1; fi
    - if grep -rni '^===\====$'; then exit 1; fi
    - if grep -rni '^>>>\>>>> '; then exit 1; fi

todos:
  extends: .checklist
  stage: checklist
  script:
    - if grep -rni '@to\do:' .; then exit 1; fi
  allow_failure: true

test package:
  image: golang:1.13-alpine
  stage: test
  before_script:
    - apk add -q make && which make
  script:
    - make test
