// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITask is an autogenerated mock type for the ITask type
type ITask struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0
func (_m *ITask) Do(_a0 context.Context) {
	_m.Called(_a0)
}
