// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	wpool "github.com/egnd/go-wpool"
	mock "github.com/stretchr/testify/mock"
)

// IWorkerFactory is an autogenerated mock type for the IWorkerFactory type
type IWorkerFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: num, pipeline
func (_m *IWorkerFactory) Execute(num uint, pipeline chan wpool.IWorker) wpool.IWorker {
	ret := _m.Called(num, pipeline)

	var r0 wpool.IWorker
	if rf, ok := ret.Get(0).(func(uint, chan wpool.IWorker) wpool.IWorker); ok {
		r0 = rf(num, pipeline)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wpool.IWorker)
		}
	}

	return r0
}
