// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	wpool "github.com/egnd/go-wpool"
	mock "github.com/stretchr/testify/mock"
)

// WorkerFactory is an autogenerated mock type for the WorkerFactory type
type WorkerFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *WorkerFactory) Execute(_a0 uint, _a1 chan wpool.IWorker) wpool.IWorker {
	ret := _m.Called(_a0, _a1)

	var r0 wpool.IWorker
	if rf, ok := ret.Get(0).(func(uint, chan wpool.IWorker) wpool.IWorker); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wpool.IWorker)
		}
	}

	return r0
}
